#!/bin/bash

cleanup () {
  [ -n "${1:-}" ] && EXIT="${1}" || EXIT=0
  [ -n "${2:-}" ] && echo "$2" >&2
  exit $EXIT
}

[ -n "${1:-}" ] && PATTERN=$1 || cleanup 1 "Missing pattern"
git filter-branch --force --index-filter "git rm --cached --ignore-unmatch $PATTERN" --prune-empty --tag-name-filter cat -- --all
git push --force --all
